config/routes.rb
StudentsCourses::Application.routes.draw do
  devise_for :students

  # match ':controller(/:action(/:id))(.:format)'
  resources :students, :courses
end

app/models/course.rb
class Course < ActiveRecord::Base
  set_primary_key 'uuid'
  attr_accessible :title, :descr
  has_and_belongs_to_many :students

  validates :title, presence: true

  before_create do
   self.id = UUIDTools::UUID.random_create.to_s 
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  set_primary_key 'uuid'
  attr_accessible :name, :email
  has_and_belongs_to_many :courses

  validates :name, :email, presence: true
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  before_create do
   self.id = UUIDTools::UUID.random_create.to_s 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def create
    @course = Course.new(params[:course])
    respond_to do |format|
      if @course.save 
        format.html { render text: "succesfully created!" }
      else 
        format.html { render text: "error occured!" }
      end
    end
  end

  def show
    @course = Course.find_by_uuid(params[:id])  
    @students = @course.students
  end

  def new
    @course = Course.create(params[:course])
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_filter :authenticate_student!, :except => [:index, :new, :show, :create]

  # /students GET
  def index
    @students = Student.all
    @student = Student.new
    respond_to do |format|
      format.html
    end
  end

  # /students POST
  def create
    @student = Student.new(params[:student])
    respond_to do |format|
      if @student.save
        format.js { render :partial => "new_student", :status => :ok, content_type: 'text/html' }
        format.html { redirect_to student_path(@student) }
      else
        format.html { render "new" }
      end
    end
  end

  # /students/1 GET
  def show
    unless @student = Student.find_by_uuid(params[:id])
      render text: "Page not found", status: 404
      # render text: params.inspect 
    end
    @courses = @student.courses
  end

  # /students/new GET
  def new
    @student = Student.new
    respond_to do |format|
      format.js { render :partial => "student_form", :status => :ok, content_type: 'text/html' }
      format.html
    end
  end

  # /students/1/edit GET
  def edit
    @student = Student.find_by_uuid(params[:id])
    @courses = Course.all - @student.courses
  end

  # /students/1 PUT
  def update
    student = Student.find_by_uuid(params[:id])
    student.name = params[:student][:name]
    student.email = params[:student][:email]

    selected = params[:selected_courses] 
    selected.each { |key, value|
      if value.to_i == 1
        student.courses << Course.find_by_uuid(key)
      end
    }
    respond_to do |format|
      if student.save 
        format.html { redirect_to :action => "show" }
      else 
        format.html { render text: "#{student.errors.first}" }
      end
    end
  end

  # /students/1 DELETE
  def destroy
    @student.find_by_uuid(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<div id="courses-list-container" class="container">

  <h1 id="courses-list-header" class="header">Courses list</h1>

  <ul id="courses-list" class="list">
    <% @courses.each do |course| %>
    <li class="courses-list-item">
      <%= link_to course.title, course_path(course), :class => "courses-list-title" %>
      <span class="courses-list-descr"><%= course.descr %></span>
    </li>
    <% end %>
  </ul>

  <div id="courses-list-new" class="new">
    <%= link_to "Create new course", { :controller => "courses", :action => "new" } %>
  </div>

  <div id="courses-list-students" class="back">
    <%= link_to "To students", students_path %>
  </div>

</div>

app/views/courses/new.html.erb
<h1>Create new course</h1>

<%= form_for (@course) do |f|%>
<div>
  <%= label_tag "Give title: " %>
  <br/>
  <%= f.text_field :title %>
</div>
<div>
  <%= label_tag "Give description: " %>
  <br/>
  <%= f.text_field :descr %>
</div>
  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<div id="course-students-container" class="container">

  <h1 id="course-students-header" class="header">Course: <%= @course.title %></h1>
  <p id="course-students-descr" class="descr"> <%= @course.descr %></p>

  <ul id="course-students" class="list">
    <% @students.each do |student| %>
    <li class="student-list-item">
      <%= link_to student.name, student_path(student), :class => "student-list-name" %>
      <span class="student-list-email"><%= student.email %></span>
    </li>
    <% end %>
  </ul>

  <!--<div id="student-list-new">
    <%= link_to "Create new student", { :controller => "students", :action => "new" } %>
  </div> -->
  <div id="courses-students-add" class="add">
    <%= link_to "Enroll new student", {:controller => "courses", :action => "edit" } %>
  </div>

  <div id="courses-students-courses" class="back">
    <%= link_to "Back to courses", courses_path %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentsCourses</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav">
    <div id="logo">
      <%= link_to "My page", student_path(current_student) %>
      <%= link_to "All students", students_path %>
      <%= link_to "All courses", courses_path%>
    </div>
    <% if student_signed_in? %>
      <p>Signed in as <%= current_student.email %>. Not you?
      <%= link_to "Sign out", destroy_student_session_path, :method => :delete %></p>
    <% else %>
      <p><%= link_to "Sign up", new_student_registration_path, :id => "sign-up" %> or <%= link_to "sign in", new_student_session_path, :id => "sign-in" %>
    <% end %>
  </div>

  <%= yield %>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/students/_new_student.html.erb
<li class="student-list-item">
  <%= link_to @student.name, student_path(@student), :class => "student-list-name" %>
  <span class="student-list-email"><%= @student.email %></span>
</li>

app/views/students/_student_form.html.erb
<%= form_for @student do |f|%>
  <div class="fieldset">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="fieldset">
    <%= label_tag :email %>
    <%= f.email_field :email %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit user parameter</h1>

<p class="responce" display="none"></p>
<%= form_for @student do |f| %>
  <div>
    <%= label_tag "Give name: " %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= label_tag "Give email: " %>
    <%= f.text_field :email %>
  </div>
  <% @courses.each do |c| %>
    <div>
      <a href="/courses/<%= c.id %>"><%= c.title %></a> <%= check_box "selected_courses", c.id %>
    </div>
  <% end %>
  <%= f.submit "Save" %>
<% end %>

app/views/students/index.html.erb
<div id="student-list-container" class="container">

  <h1 id="student-list-header" class="header">Students list</h1>

  <ul id="student-list" class="list">
    <% @students.each do |student| %>
    <li class="student-list-item">
      <%= link_to student.name, student_path(student), :class => "student-list-name" %>
      <span class="student-list-email"><%= student.email %></span>
    </li>
    <% end %>
  </ul>

  <!--<div id="student_list_nav">
    <button id="prev" data-dir="prev">Previous</button>
    <button id="next" data-dir="next">Next</button>
  </div>
  -->
  <div id="student-list-new" class="new">
    <%= link_to "Create new student", { :controller => "students", :action => "new" } %>
  </div>
  
  <div id="registration-form" style="display: none">
  </div>

  <div id="student-list-courses" class="back">
    <%= link_to "To courses", courses_path %>
  </div>

</div>

app/views/students/new.html.erb
<div id="new-student-container" class="container">

  <h1 id="new-student-header" class="header">Create new student</h1>
  <% if !@student.errors.empty? %>
    <% @student.errors.each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>

  <%= form_for @student do |f|%>
    <div class="fieldset">
      <%= label_tag "Give name: " %>
      <%= f.text_field :name %>
    </div>
    <div class="fieldset">
      <%= label_tag "Give email: " %>
      <%= f.text_field :email %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/students/show.html.erb
<div id="student-courses-container" class="container">
  <h1 id="student-courses-title" class="header">Hello, <%= @student.name %>! </h1>
  <h3>Your courses:</h3>

  <ul id="student-courses-list" class="list">
    <% @courses.each do |course| %>
    <li class="courses-list-item">
      <%= link_to course.title, course_path(course), :class => "courses-list-title" %>
      <span class="courses-list-descr"><%= course.descr %></span>
    </li>
    <% end %>
  </ul>

  <div id="student-courses-edit" class="edit">
    <%= link_to "Edit student", { :controller => "students", :action => "edit" } %>
  </div>

  <div id="student-courses-delete" class="delete">
    <%= link_to "Kill student", { :controller => "students", :action => "destroy" } %>
  </div>

  <div id="student-courses" class="back">
    <%= link_to "Back to students", students_path %>
  </div>
</div>

app/views/students/update.html.erb
<h1> Updated </h1>